version: "3"

services:
  admin_db:
    image: mysql:5.7
    container_name: ifind_admin_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ifind_admin
    ports:
      - "6603:3306"
    volumes:
      - ./.mysql/my.cnf:/etc/my.cnf
      - ./.mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
